### ISSUE TITLE
Feature request: API to reach registered events and errors upon non-existing subscription

### ISSUE THREAD

**Issue by mensfeld** [dry-rb/dry-monitor#11]
Hey guys,

We use dry-monitor together with dry-events in karafka. In order to provide a "safe" API (safe in terms of typo mistakes etc) we've implemented two additional methods for the monitor that could be useful when working with it. Would it fit as a PR in this library?

```ruby
      # Allows us to subscribe to events with a code that will be yielded upon events
      # @param event_name_or_listener [String, Object] name of the event we want to subscribe to
      #   or a listener if we decide to go with object listener
      def subscribe(event_name_or_listener)
        return super unless event_name_or_listener.is_a?(String)
        return super if available_events.include?(event_name_or_listener)
        raise Errors::UnregisteredMonitorEvent, event_name_or_listener
      end

      # @return [Array<String>] names of available events to which we can subscribe
      def available_events
        __bus__.events.keys
      end
```

I  believe that this behavior would prevent users from subscribing to non-registered events.

Whole monitor can be found here: https://github.com/karafka/karafka/blob/master/lib/karafka/instrumentation/monitor.rb

**Comment by GustavoCaso** [comment]
I can help with this one 😄

**Comment by mensfeld** [comment]
@GustavoCaso well it shouldn't be that hard to implement as it is already there :D
@solnic since you've added the tags I guess I can implement those as described above, right?

**Comment by solnic** [comment]
Yes, but I reckon this should go into dry-events lib
