### ISSUE TITLE
rack not found in the dependencies - cannot load such file -- rack/utils

### ISSUE THREAD

**Issue by mensfeld** [dry-rb/dry-monitor#16]
Here we require rack: https://github.com/dry-rb/dry-monitor/blob/master/lib/dry/monitor/rack/middleware.rb
but dry-monitor does not have it in the dependencies, so when rack is not used in the project it fails with this error:

```
LoadError:
  cannot load such file -- rack/utils
```

@solnic do we want to add it as a dep or make rack/middleware as a plugin same as rouge?

**Comment by solnic** [comment]
> @solnic do we want to add it as a dep or make rack/middleware as a plugin same as rouge?

it should be a plugin/extension like rouge
