### ISSUE TITLE
0.3.0 does not play well with dry-web

### ISSUE THREAD

**Issue by alexandru-calinoiu** [dry-rb/dry-monitor#18]
Simple container class;

```ruby
require 'dry/web/container'
require 'dry/system/components'

module NotificationService
  class Container < Dry::Web::Container

    configure do
      config.name = :notification_service
      config.listeners = true
      config.default_namespace = 'api'
      config.auto_register = %w[lib/api]
    end
end
```

Line `  class Container < Dry::Web::Container` will throw:

```
  uninitialized constant Dry::Monitor::Rack
```

The full stack trace is:

```
NameError:
  uninitialized constant Dry::Monitor::Rack
  Did you mean?  Rack
# ./vendor/bundle/ruby/2.4.0/gems/dry-web-0.8.0/lib/dry/web/container.rb:25:in `register_rack_monitor'
# ./vendor/bundle/ruby/2.4.0/gems/dry-web-0.8.0/lib/dry/web/container.rb:16:in `block in inherited'
# ./vendor/bundle/ruby/2.4.0/gems/dry-system-0.10.1/lib/dry/system/container.rb:107:in `instance_eval'
# ./vendor/bundle/ruby/2.4.0/gems/dry-system-0.10.1/lib/dry/system/container.rb:107:in `block in configure'
# ./vendor/bundle/ruby/2.4.0/gems/dry-system-0.10.1/lib/dry/system/container.rb:107:in `each'
# ./vendor/bundle/ruby/2.4.0/gems/dry-system-0.10.1/lib/dry/system/container.rb:107:in `configure'
# ./system/notification_service/container.rb:11:in `<class:Container>'
```

**Comment by mensfeld** [comment]
Can you:

```ruby
require 'dry-monitor'
Dry::Monitor.load_extensions(:rack)
```

rack is not an extension to monitor, to allow non rack apps to use it as well.

**Comment by flash-gordon** [comment]
I guess dry-web should do it itself

**Comment by mensfeld** [comment]
True. I will fix that one as soon as @alexandru-calinoiu confirms that it helps.

**Comment by alexandru-calinoiu** [comment]
> Can you:
> 
> ```ruby
> require 'dry-monitor'
> Dry::Monitor.load_extensions(:rack)
> ```
> 
> rack is not an extension to monitor, to allow non rack apps to use it as well.

I've already tried this this and it does not help, maybe I did something wrong :(

**Comment by mensfeld** [comment]
Ok. Looking into that now. Sorry for the trouble.

**Comment by mensfeld** [comment]
@alexandru-calinoiu can you confirm that this works?

```ruby
require 'dry/web/container'
require 'dry/system/components'
require 'dry-monitor'
Dry::Monitor.load_extensions(:rack)

module NotificationService
  class Container < Dry::Web::Container

    configure do
      config.name = :notification_service
      config.listeners = true
      config.default_namespace = 'api'
      config.auto_register = %w[lib/api]
    end
  end
end
```
and the Gemfile:

```ruby
source 'https://rubygems.org'

gem 'rack'
gem 'dry-monitor'
gem 'dry-web'
```

**Comment by alexandru-calinoiu** [comment]
> @alexandru-calinoiu can you confirm that this works?
> 
> ```ruby
> require 'dry/web/container'
> require 'dry/system/components'
> require 'dry-monitor'
> Dry::Monitor.load_extensions(:rack)
> 
> module NotificationService
>   class Container < Dry::Web::Container
> 
>     configure do
>       config.name = :notification_service
>       config.listeners = true
>       config.default_namespace = 'api'
>       config.auto_register = %w[lib/api]
>     end
>   end
> end
> ```
> 
> and the Gemfile:
> 
> ```ruby
> source 'https://rubygems.org'
> 
> gem 'rack'
> gem 'dry-monitor'
> gem 'dry-web'
> ```

I can confirm this works, thanks for the response.

**Comment by mensfeld** [comment]
I will close it as it is now a `dry-web` issue.

**Comment by mihairadulescu** [comment]
Dry::Monitor.load_extensions(:rack, :sql)
