### ISSUE TITLE
Conflict with notifications relation

### ISSUE THREAD

**Issue by alexandru-calinoiu** [dry-rb/dry-monitor#26]
I have an notifications table in my database, after adding a `Notifications` relation I started receiving very strange errors.

Upon investigation it turns out that instrumentation will try to log to my relation instead of `Dry::Monitor::Notifications`

**Comment by mensfeld** [comment]
Smells like a code scope visibility problem, not a dry-monitor issue. Please check your code and please provide a reproducible example with more details. Otherwise, there is no way to even try to approach that.

**Comment by alexandru-calinoiu** [comment]
You are right I've traced the problem in rom-sql now.
