### ISSUE TITLE
Zeitwerk error under in Rails 7 / Ruby 3.1.2

### ISSUE THREAD

**Issue by Azdaroth** [dry-rb/dry-monitor#49]
## Describe the bug

When running `bin/rails zeitwerk:check` I'm getting:

``` rb
Hold on, I am eager loading the application.
expected file /Users/azdaroth/.rvm/gems/ruby-3.1.2/gems/dry-monitor-0.6.1/lib/dry/monitor/version.rb to define constant Dry::Monitor::Version
```

Has anyone else experiences this issue?

## My environment

- Rails version 7.0.3.1
- Ruby version: 3.1.2

**Comment by Azdaroth** [comment]
The issue might be a bit more complex actually. We are using a private gem that uses dry-monitor, but also, one of the dependencies use dry-monitor as well, so there is no need to require it and having it in gemspec at all (well, of course as long as this dependency uses dry-monitor). When we removed dry-monitor from gemspec , it fixed the issue.

**Comment by solnic** [comment]
Thanks for reporting this. I think we need to configure zeitwerk to handle `version.rb` in a special way as this file defines `Dry::Monitor::VERSION` rather than `Dry::Monitor::Version`.

**Comment by flash-gordon** [comment]
@Azdaroth I pushed 0.6.2 with a fix, please test it out

**Comment by Azdaroth** [comment]
@flash-gordon Thanks for submitting a fix! Now I'm getting `LoadError: cannot load such file -- rouge/util`, which can be fixed  by adding `rouge` gem to the Gemfile

**Comment by solnic** [comment]
uhm, this is supposed to be optional only when you want colorized SQL logging, I suspect that auto-loading is triggered in a way that ends up requiring the logging extension which depends on rouge 😞

**Comment by flash-gordon** [comment]
I think we just need to opt-out extensions from autoloading, I'll take a look

**Comment by flash-gordon** [comment]
I pushed 0.6.3 with a fix

**Comment by Azdaroth** [comment]
@flash-gordon Thanks for the fix, everything looks fine now!

**Comment by flash-gordon** [comment]
Awesome
