### ISSUE TITLE
Make rouge an optional dependency

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-monitor#9]
SQL logger can be [configured with colorized output **disabled**](https://github.com/dry-rb/dry-monitor/blob/master/lib/dry/monitor/sql/logger.rb#L22), but we have a hard dep on rouge, which turned out to be a heavy gem, so we should make it optional.

I imagine that we could lazy-require rouge when it's needed, and raise a nice exception if it failed to require it (so rescue `LoadError` and re-raise something nicer).

See https://discourse.dry-rb.org/t/improvement-better-memory-usage-in-dry-monitor/468

**Comment by davydovanton** [comment]
I can do it 👍

**Comment by mensfeld** [comment]
@davydovanton I need it. I can do it. Can I take over?

**Comment by solnic** [comment]
@mensfeld sure, looks like I failed to give feedback in the related PR, so I've been a blocker here. Let's revisit this.

**Comment by mensfeld** [comment]
@solnic I would make the whole sql logger optional. I use dry monitor in several systems. None of which has SQL ;)

**Comment by davydovanton** [comment]
@mensfeld hey, of course. If you want we can create 🍐 programming session with it. WDYT?

**Comment by mensfeld** [comment]
Yeah that would be cool. Monday maybe? We can arrange that via FB!

**Comment by davydovanton** [comment]
monday will great for me! let's connect via FB!
